Repository conqueror-G/Mars-monitoring-system, pull requests merged in 2022-08, with the labels that each got.

#5 [34기 전지현] Feature/extra work - 디바이스 기능구현
  public/data/deviceDetail/device_repair.json
  public/data/equipmentDetail.json
  public/data/homeData.json
  src/components/detailInfo/DetailInfo.tsx
  src/components/detailList/DetailList.tsx
  src/components/editBox/MakeInput.tsx
  src/components/editBox/MakeSelectBox.tsx
  src/components/googleMap/MarkerRender.tsx
  src/components/toast/Toast.tsx
  src/config.tsx
  src/pages/deviceDetail/DeviceDetail.tsx
  src/pages/deviceDetail/components/DeviceEdit.tsx
  src/pages/deviceDetail/components/DeviceInfo.tsx
  src/pages/deviceDetail/components/DeviceInstallLog.tsx
  src/pages/deviceDetail/components/DeviceRepairAdd.tsx
  src/pages/deviceDetail/components/DeviceRepairLog.tsx
  src/pages/deviceDetail/components/DeviceReplaceAdd.tsx
  src/pages/deviceDetail/components/DeviceReplaceLog.tsx
  src/pages/equipmentDetail/EquipmentDetail.tsx
  src/pages/equipmentDetail/components/EquipEdit.tsx
  src/pages/equipmentDetail/components/EquipInstallLog.tsx
  src/pages/equipmentDetail/components/EquipRepairAdd.tsx
  src/pages/equipmentDetail/components/EquipRepairLog.tsx
  src/pages/equipmentDetail/components/EquipmentInfo.tsx
  src/pages/home/Home.tsx
  src/pages/home/components/alarmData/AlarmData.tsx
  src/stores/deviceDetailData.tsx
  src/stores/equipDetailDatas.tsx
  src/useStore.tsx
Labels: ✨ Feature, 📬 API

#2 [김민석 feature/common-edit-config-router] MODIFY: Routers, MainLayoutRoutes, config 변경
  src/MainLayoutRoutes.tsx
  src/Router.tsx
  src/config.tsx
Labels: ⚙ Setting

#3 [김민석 release/login] Refactor: 상태관리
  src/pages/adminMapping/AdminMapping.tsx
  src/pages/login/LoginForm.tsx
  src/pages/login/components/input/Input.tsx
  src/stores/login/enteredUserInfo.tsx
  src/stores/login/pwVisibilityToggle.tsx
  src/stores/login/validMessageToggle.tsx
  src/useStore.tsx
Labels: 📬 API, 🔨 Refactor

#4 [김민석 release/nav] Refactor: store사용 및 웹소켓
  src/components/sideNav/SideNav.css
  src/components/sideNav/SideNav.tsx
  src/components/sideNav/components/contractionMenuTab/ContractionMenuTab.tsx
  src/components/sideNav/components/contractionNav/ContractionNav.tsx
  src/components/sideNav/components/detailDownMenuTab/DetailDownMenuTab.tsx
  src/components/sideNav/components/detailNav/DetailNav.tsx
  src/components/sideNav/data/contractionMenuTabData.tsx
  src/components/sideNav/data/detailMenuTabData.tsx
  src/components/topNav/TopNav.tsx
  src/components/topNav/components/alarmInterface/AlarmInterface.tsx
  src/components/topNav/components/alarmModal/AlarmModal.tsx
  src/components/topNav/components/currentPath/CurrentPath.tsx
  src/components/topNav/components/logoutModal/LogoutModal.tsx
  src/stores/sideNav/isSideNavToggle.tsx
  src/stores/topNav/isTopNavIsToggle.tsx
  src/stores/topNav/messageId.tsx
  src/stores/topNav/pathNumbers.tsx
  src/stores/usersInfo.tsx
  src/useStore.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#6 Readme 작성
  README.md
Labels: 📃 Docs

#7 [doc/readme] MODIFY: 구현기능, 이슈 공유
  README.md
Labels: 📃 Docs

#8 [김민석 doc/readme] README 전체적으로 다시 작성
  README.md
Labels: 📃 Docs
